// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuadroApp.Data;

#nullable disable

namespace QuadroApp.Migrations.Npgsql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsGroep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AfwerkingsGroepen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsOptie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AfvalPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("AfwerkingsGroepId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("boolean");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("KostprijsPerM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("VasteKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<char>("Volgnummer")
                        .HasColumnType("character(1)");

                    b.Property<int>("WerkMinuten")
                        .HasColumnType("integer");

                    b.Property<decimal>("WinstMarge")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.HasIndex("AfwerkingsGroepId", "Volgnummer", "Kleur")
                        .IsUnique();

                    b.ToTable("AfwerkingsOpties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AfwerkingsOptieId")
                        .HasColumnType("integer");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStandaard")
                        .HasColumnType("boolean");

                    b.Property<string>("Kleur")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AfwerkingsOptieId", "Beschrijving")
                        .IsUnique();

                    b.ToTable("AfwerkingsVarianten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EntiteitId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntiteitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gebruiker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Wijzigingen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tijdstip");

                    b.HasIndex("EntiteitType", "EntiteitId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Factuur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AangenomenDoorInitialen")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("AfhaalDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BijgewerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExportPad")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FactuurDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactuurNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GeplandeDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBtwVrijgesteld")
                        .HasColumnType("boolean");

                    b.Property<int>("Jaar")
                        .HasColumnType("integer");

                    b.Property<string>("KlantAdres")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("KlantBtwNummer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("KlantNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("KortingBedragExcl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("KortingPct")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("OfferteId")
                        .HasColumnType("integer");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotaalBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotaalExclBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("VervalDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VolgNr")
                        .HasColumnType("integer");

                    b.Property<decimal>("VoorschotBedrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("WerkBonId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FactuurNummer")
                        .IsUnique();

                    b.HasIndex("OfferteId")
                        .IsUnique();

                    b.HasIndex("WerkBonId")
                        .IsUnique();

                    b.HasIndex("Jaar", "VolgNr")
                        .IsUnique();

                    b.ToTable("Facturen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.FactuurLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aantal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BtwPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Eenheid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FactuurId")
                        .HasColumnType("integer");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PrijsExcl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Sortering")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotaalBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotaalExcl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotaalIncl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FactuurId");

                    b.ToTable("FactuurLijnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.GeblokkeerdeDag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reden")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Datum")
                        .IsUnique();

                    b.ToTable("GeblokkeerDagen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GebruikersNaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LaatsteLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MoetWachtwoordWijzigen")
                        .HasColumnType("boolean");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("VolledigeNaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WachtwoordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikersNaam")
                        .IsUnique();

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportRowLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("IssuesJson")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("ImportRowLogs");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ImportSessions");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Instelling", b =>
                {
                    b.Property<string>("Sleutel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Waarde")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Sleutel");

                    b.ToTable("Instellingen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BtwNummer")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GearchiveerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gemeente")
                        .HasColumnType("text");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("boolean");

                    b.Property<string>("Nummer")
                        .HasColumnType("text");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("Straat")
                        .HasColumnType("text");

                    b.Property<string>("Telefoon")
                        .HasColumnType("text");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Leverancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("Leveranciers");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AantalMeterBesteld")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("AantalMeterOntvangen")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("BestelVorm")
                        .HasColumnType("integer");

                    b.Property<int>("LeverancierBestellingId")
                        .HasColumnType("integer");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RedenType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TypeLijstId")
                        .HasColumnType("integer");

                    b.Property<int?>("WerkBonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierBestellingId");

                    b.HasIndex("TypeLijstId");

                    b.HasIndex("WerkBonId");

                    b.ToTable("LeverancierBestelLijnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AangemaaktDoor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BestelNummer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("BesteldOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OntvangenOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("VerwachteLeverdatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BestelNummer")
                        .IsUnique();

                    b.HasIndex("LeverancierId");

                    b.ToTable("LeverancierBestellingen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AfhaalDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BtwBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeplandeDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GeschatteMinuten")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVoorschotBetaald")
                        .HasColumnType("boolean");

                    b.Property<int?>("KlantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KortingPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerPrijsIncl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("SubtotaalExBtw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VoorschotBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Offertes");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.OfferteArchief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GearchiveerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HadWerkBon")
                        .HasColumnType("boolean");

                    b.Property<int?>("HersteldNaarOfferteId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHersteld")
                        .HasColumnType("boolean");

                    b.Property<int>("Jaar")
                        .HasColumnType("integer");

                    b.Property<int?>("KlantId")
                        .HasColumnType("integer");

                    b.Property<string>("KlantNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OfferteDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrigineleOfferteId")
                        .HasColumnType("integer");

                    b.Property<string>("Reden")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusOpMoment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GearchiveerdOp");

                    b.HasIndex("Jaar");

                    b.HasIndex("OrigineleOfferteId");

                    b.ToTable("OfferteArchieven");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.OfferteRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalStuks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AfgesprokenPrijsExcl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AfhaalDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BreedteCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BtwBedrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiepteKernId")
                        .HasColumnType("integer");

                    b.Property<int?>("DiepteKernVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtraPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ExtraWerkMinuten")
                        .HasColumnType("integer");

                    b.Property<int?>("GlasId")
                        .HasColumnType("integer");

                    b.Property<int?>("GlasVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HoogteCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("InlegBreedteCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InlegHoogteCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Korting")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("LegacyCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("OfferteId")
                        .HasColumnType("integer");

                    b.Property<int?>("OpklevenId")
                        .HasColumnType("integer");

                    b.Property<int?>("OpklevenVariantId")
                        .HasColumnType("integer");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PassePartout1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("PassePartout1VariantId")
                        .HasColumnType("integer");

                    b.Property<int?>("PassePartout2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("PassePartout2VariantId")
                        .HasColumnType("integer");

                    b.Property<int?>("RugId")
                        .HasColumnType("integer");

                    b.Property<int?>("RugVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotaalExBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotaalExcl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TypeLijstId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiepteKernId");

                    b.HasIndex("DiepteKernVariantId");

                    b.HasIndex("GlasId");

                    b.HasIndex("GlasVariantId");

                    b.HasIndex("OfferteId");

                    b.HasIndex("OpklevenId");

                    b.HasIndex("OpklevenVariantId");

                    b.HasIndex("PassePartout1Id");

                    b.HasIndex("PassePartout1VariantId");

                    b.HasIndex("PassePartout2Id");

                    b.HasIndex("PassePartout2VariantId");

                    b.HasIndex("RugId");

                    b.HasIndex("RugVariantId");

                    b.HasIndex("TypeLijstId");

                    b.ToTable("OfferteRegels");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.TypeLijst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AfvalPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("BreedteCm")
                        .HasColumnType("integer");

                    b.Property<decimal>("GereserveerdeVoorraadMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("HerbestelNiveauMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("InBestellingMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("InventarisKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LaatsteUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LaatsteVoorraadCheckOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Levcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumVoorraad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Opmerking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrijsPerMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VasteKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("VoorraadMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("WerkMinuten")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WinstFactor")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.ToTable("TypeLijsten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.VoorraadAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Bericht")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BronReferentie")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("LaatstHerinnerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TypeLijstId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VolgendeHerinneringOp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TypeLijstId");

                    b.ToTable("VoorraadAlerts");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.VoorraadMutatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AantalMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("LeverancierBestelLijnId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MutatieDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutatieType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Referentie")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("TypeLijstId")
                        .HasColumnType("integer");

                    b.Property<int?>("WerkBonId")
                        .HasColumnType("integer");

                    b.Property<int?>("WerkTaakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierBestelLijnId");

                    b.HasIndex("TypeLijstId");

                    b.HasIndex("WerkBonId");

                    b.HasIndex("WerkTaakId");

                    b.ToTable("VoorraadMutaties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AfhaalDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BijgewerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferteId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("StockReservationProcessed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotaalPrijsIncl")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OfferteId")
                        .IsUnique();

                    b.ToTable("WerkBonnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBonArchief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnuleringsReden")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("GearchiveerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HersteldNaarOfferteId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHersteld")
                        .HasColumnType("boolean");

                    b.Property<int?>("KlantId")
                        .HasColumnType("integer");

                    b.Property<string>("KlantNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OfferteDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferteId")
                        .HasColumnType("integer");

                    b.Property<string>("OfferteStatusOpMoment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("OrigineleWerkBonId")
                        .HasColumnType("integer");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotaalPrijsIncl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WerkBonStatusOpMoment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("GearchiveerdOp");

                    b.HasIndex("OfferteId");

                    b.HasIndex("OrigineleWerkBonId");

                    b.ToTable("WerkBonArchieven");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkTaak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BenodigdeMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("BestelDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuurMinuten")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeplandTot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeplandVan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBesteld")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpVoorraad")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeverancierBestelLijnId")
                        .HasColumnType("integer");

                    b.Property<int?>("OfferteRegelId")
                        .HasColumnType("integer");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Resource")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("VoorraadStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WeekNotitie")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("WerkBonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeplandVan");

                    b.HasIndex("LeverancierBestelLijnId");

                    b.HasIndex("OfferteRegelId");

                    b.HasIndex("WerkBonId");

                    b.ToTable("WerkTaken");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsOptie", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.AfwerkingsGroep", "AfwerkingsGroep")
                        .WithMany("Opties")
                        .HasForeignKey("AfwerkingsGroepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.Leverancier", "Leverancier")
                        .WithMany()
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AfwerkingsGroep");

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsVariant", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Optie")
                        .WithMany("Varianten")
                        .HasForeignKey("AfwerkingsOptieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optie");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Factuur", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Offerte", "Offerte")
                        .WithOne()
                        .HasForeignKey("QuadroApp.Model.DB.Factuur", "OfferteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuadroApp.Model.DB.WerkBon", "WerkBon")
                        .WithOne()
                        .HasForeignKey("QuadroApp.Model.DB.Factuur", "WerkBonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Offerte");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.FactuurLijn", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Factuur", "Factuur")
                        .WithMany("Lijnen")
                        .HasForeignKey("FactuurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factuur");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportRowLog", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.ImportSession", "ImportSession")
                        .WithMany("RowLogs")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSession");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelLijn", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.LeverancierBestelling", "LeverancierBestelling")
                        .WithMany("Lijnen")
                        .HasForeignKey("LeverancierBestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.TypeLijst", "TypeLijst")
                        .WithMany("LeverancierBestelLijnen")
                        .HasForeignKey("TypeLijstId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.WerkBon", "WerkBon")
                        .WithMany()
                        .HasForeignKey("WerkBonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LeverancierBestelling");

                    b.Navigation("TypeLijst");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelling", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Leverancier", "Leverancier")
                        .WithMany("Bestellingen")
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Klant", "Klant")
                        .WithMany("Offertes")
                        .HasForeignKey("KlantId");

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.OfferteRegel", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "DiepteKern")
                        .WithMany()
                        .HasForeignKey("DiepteKernId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "DiepteKernVariant")
                        .WithMany()
                        .HasForeignKey("DiepteKernVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Glas")
                        .WithMany()
                        .HasForeignKey("GlasId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "GlasVariant")
                        .WithMany()
                        .HasForeignKey("GlasVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.Offerte", "Offerte")
                        .WithMany("Regels")
                        .HasForeignKey("OfferteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Opkleven")
                        .WithMany()
                        .HasForeignKey("OpklevenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "OpklevenVariant")
                        .WithMany()
                        .HasForeignKey("OpklevenVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "PassePartout1")
                        .WithMany()
                        .HasForeignKey("PassePartout1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "PassePartout1Variant")
                        .WithMany()
                        .HasForeignKey("PassePartout1VariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "PassePartout2")
                        .WithMany()
                        .HasForeignKey("PassePartout2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "PassePartout2Variant")
                        .WithMany()
                        .HasForeignKey("PassePartout2VariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Rug")
                        .WithMany()
                        .HasForeignKey("RugId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsVariant", "RugVariant")
                        .WithMany()
                        .HasForeignKey("RugVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.TypeLijst", "TypeLijst")
                        .WithMany()
                        .HasForeignKey("TypeLijstId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DiepteKern");

                    b.Navigation("DiepteKernVariant");

                    b.Navigation("Glas");

                    b.Navigation("GlasVariant");

                    b.Navigation("Offerte");

                    b.Navigation("Opkleven");

                    b.Navigation("OpklevenVariant");

                    b.Navigation("PassePartout1");

                    b.Navigation("PassePartout1Variant");

                    b.Navigation("PassePartout2");

                    b.Navigation("PassePartout2Variant");

                    b.Navigation("Rug");

                    b.Navigation("RugVariant");

                    b.Navigation("TypeLijst");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.TypeLijst", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Leverancier", "Leverancier")
                        .WithMany("TypeLijsten")
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.VoorraadAlert", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.TypeLijst", "TypeLijst")
                        .WithMany("VoorraadAlerts")
                        .HasForeignKey("TypeLijstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TypeLijst");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.VoorraadMutatie", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.LeverancierBestelLijn", "LeverancierBestelLijn")
                        .WithMany("VoorraadMutaties")
                        .HasForeignKey("LeverancierBestelLijnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuadroApp.Model.DB.TypeLijst", "TypeLijst")
                        .WithMany("VoorraadMutaties")
                        .HasForeignKey("TypeLijstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.WerkBon", "WerkBon")
                        .WithMany()
                        .HasForeignKey("WerkBonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuadroApp.Model.DB.WerkTaak", "WerkTaak")
                        .WithMany()
                        .HasForeignKey("WerkTaakId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LeverancierBestelLijn");

                    b.Navigation("TypeLijst");

                    b.Navigation("WerkBon");

                    b.Navigation("WerkTaak");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Offerte", "Offerte")
                        .WithOne("WerkBon")
                        .HasForeignKey("QuadroApp.Model.DB.WerkBon", "OfferteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offerte");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkTaak", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.LeverancierBestelLijn", "LeverancierBestelLijn")
                        .WithMany()
                        .HasForeignKey("LeverancierBestelLijnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuadroApp.Model.DB.OfferteRegel", "OfferteRegel")
                        .WithMany()
                        .HasForeignKey("OfferteRegelId");

                    b.HasOne("QuadroApp.Model.DB.WerkBon", "WerkBon")
                        .WithMany("Taken")
                        .HasForeignKey("WerkBonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeverancierBestelLijn");

                    b.Navigation("OfferteRegel");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsGroep", b =>
                {
                    b.Navigation("Opties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsOptie", b =>
                {
                    b.Navigation("Varianten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Factuur", b =>
                {
                    b.Navigation("Lijnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportSession", b =>
                {
                    b.Navigation("RowLogs");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Klant", b =>
                {
                    b.Navigation("Offertes");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Leverancier", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("TypeLijsten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelLijn", b =>
                {
                    b.Navigation("VoorraadMutaties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.LeverancierBestelling", b =>
                {
                    b.Navigation("Lijnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.Navigation("Regels");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.TypeLijst", b =>
                {
                    b.Navigation("LeverancierBestelLijnen");

                    b.Navigation("VoorraadAlerts");

                    b.Navigation("VoorraadMutaties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.Navigation("Taken");
                });
#pragma warning restore 612, 618
        }
    }
}
